### ISSUE TITLE
Lspatch使用

### ISSUE THREAD

**Issue by imod-commission** [akemimadoka/UmaPyogin-Android#2]
能夠透過lspatch免root使用插件, 但無法打开app设置（开/关漢化及60fps), 只能於lspatch完全关掉

**Comment by imod-commission** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{moe.madoka.umapyogin_android/moe.madoka.umapyogin_android.MainActivity}: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3308)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
	at android.app.ContextImpl.checkMode(ContextImpl.java:2636)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:463)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:453)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:188)
	at moe.madoka.umapyogin_android.MainActivity.onCreate(MainActivity.kt:78)
	at android.app.Activity.performCreate(Activity.java:7893)
	at android.app.Activity.performCreate(Activity.java:7880)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)
	... 11 more
